# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'zach pollard'
tagline:             'the website'
description:         'Look ma, I have a website!'
baseurl:             ''
paginate:            5
markdown:            kramdown

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : 1..6
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# About/contact
author:
  name:              zach pollard
  url:               https://zachpollard.github.io
  email:             zacharie.pollard.1996@email.com

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/codebam/tmsc-workshop
